---

- name: "configuration play." 
  hosts: backend
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: Confirm Server Access
      shell: echo curl ifconfig.io

  post_tasks:
     - shell: echo "Done configuring server"

  # Get the environment variables from CircleCI and add to the EC2 instance
  environment:
    - DEBIAN_FRONTEND: noninteractive
    - DOCKER_ACCOUNT: "{{ lookup('env', '$DOCKER_ACCOUNT')}}"

  roles:
    - configure-server
    #- configure-prometheus-node-exporter

