---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: Confirm Server Access
      shell: echo curl ifconfig.io
    #- name: "wait 600 seconds for target connection to become reachable/usable."
    #- name: "install python for Ansible."
    #  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    #  changed_when: False

  post_tasks:
     - shell: echo 'I":" Done configuring nginx web server...'

  # Get the environment variables from CircleCI and add to the EC2 instance
  environment:
    - DEBIAN_FRONTEND: noninteractive
    - DOCKER_ACCOUNT: "{{ lookup('env', '$DOCKER_ACCOUNT')}}"

  roles:
    - configure-server
    - configure-prometheus-node-exporter

