---

- name: Backend Server Deployment Play
  hosts: backend
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  # Get the environment variables from CircleCI and add to the EC2 instance
  environment:
    - DEBIAN_FRONTEND: noninteractive
    - DOCKER_ACCOUNT: "{{ lookup('env', '$DOCKER_ACCOUNT')}}"
    - DOCKER_PASSWORD: "{{ lookup('env', '$DOCKER_PASSWORD')}}"

  roles:
    - deploy

