Description: >
  Cloudfront distribution for Capstone

Parameters:
  BackendDNS:
    Description: Updated backend endpoint
    Type: String

Resources:   
  WebpageCDN:
    #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-distribution.html
    Type: AWS::CloudFront::Distribution  
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub "${BackendDNS}"
            Id: CapstoneOrigin
            CustomOriginConfig:
              - OriginProtocolPolicy: http-only

        Enabled: True
Outputs:
  BackendEndpoint:
    Value: !Sub ${BackendDNS}
    Description: Backend Endpoint
