Description: >
  Cloudfront distribution for Capstone

Parameters:
  BackendDNS:
    Description: Updated backend endpoint
    Type: String

Resources:   
  WebpageCDN:
    #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-distribution.html
    Type: AWS::CloudFront::Distribution  
    Properties:
      DistributionConfig:
        Enabled: True
        Origins:
          - Id: CapstoneOrigin
            DomainName: !Sub "${BackendDNS}"
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: False
          TargetOriginId: CapstoneOrigin
          ViewerProtocolPolicy: allow-all
        
Outputs:
  BackendEndpoint:
    Value: !Sub ${BackendDNS}
    Description: Backend Endpoint
  ClopudFrontEndpoint:
    Value: !GetAtt WebpageCDN.DomainName
    Description: CloudFront DNS
