version: 2.1

jobs:
  build-images:
    docker:
      - image: circleci/node:13.8.0    #circleci/python:3.6.7-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt update -y
            sudo apt install -y vim
            sudo pip install --upgrade pip
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            sudo chmod +x /bin/hadolint
      - run:
          name: Build Images
          command: |
            cd /home/circleci/repo
            docker build -f ./build/hello_app/apache.Dockerfile --tag hello_app ./build/hello_app
      - run:
          name: Lint Images
          command: |
            cd /home/circleci/repo
            hadolint ./build/hello_app/apache.Dockerfile
            
workflows:
  default:
    jobs:
      - build-images
      #- test-images:
      #    requires: [build-images]