version: 2.1

orbs:
  slack: circleci/slack@4.1

jobs:
  build-images:
    machine: true           #https://circleci.com/docs/2.0/building-docker-images/
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt update -y
            sudo apt install -y vim
      - run:
          name: Build Images
          command: |
            cd ~/repo
            docker build -f apache.Dockerfile --tag hello_app .
      - run: 
          name: Tag images
          command: |
            echo "$DOCKER_PASSWORD" > docker_password.txt
            cat docker_password.txt | docker login --username $DOCKER_ACCOUNT --password-stdin
            docker tag hello_app:latest $DOCKER_ACCOUNT/hello_app
      - run: 
          name: Push images
          command: |
            docker push cbath/hello_app

  test-images:
    machine: true 
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            sudo chmod +x /bin/hadolint
      - run:
          name: Lint Images
          command: |
            cd /home/circleci/repo
            hadolint apache.Dockerfile
      - run:
          name: Download Images
          command: |
            echo "$DOCKER_PASSWORD" > docker_password.txt
            cat docker_password.txt | docker login --username $DOCKER_ACCOUNT --password-stdin
            docker pull $DOCKER_ACCOUNT/hello_app
      - run:
          name: Test Images
          command: |
            docker container run -d -p 8080:80  $DOCKER_ACCOUNT/hello_app
            curl localhost:8080
      - slack/notify:
          channel: 'udacity-ci-cd'
          event: fail
          template: basic_fail_1
      
  # https://docs.docker.com/engine/scan/
  #scan-images:
  #  machine: true 
  #  working_directory: ~/repo
  #  steps:
  #    - run:
  #        name: Download Images
  #        command: |
  #          echo "$DOCKER_PASSWORD" > docker_password.txt
  #          cat docker_password.txt | docker login --username $DOCKER_ACCOUNT --password-stdin
  #          docker pull $DOCKER_ACCOUNT/hello_app
  #          docker image tag $DOCKER_ACCOUNT/hello_app hello_app:latest
  #    - run:
  #        name: Scan Images
  #        command: |
  #            docker scan hello_app

  create-infrastructure:
    working_directory: ~/repo
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          command: yum install -y tar gzip
      - run:
          name: Create Backend Infrastructure
          command: |
              export dir=~/repo/deploy/cloudformation/servers
              aws cloudformation deploy \
              --template-file $dir/servers.yml \
              --stack-name "capstone-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
              --tags project=capstone
      - run:
          name: Add backend ip to ansible inventory
          command: |
            BACKEND_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=capstone-backend-${CIRCLE_WORKFLOW_ID:0:7}" --query "Reservations[*].Instances[*].{public_ip:PublicIpAddress}" --output text)
            echo $BACKEND_IP >> ~/repo/deploy/ansible/inventory.txt
            echo $BACKEND_IP
      # Save workspace for subsequent jobs (i.e. test)
      - persist_to_workspace:
          root: ~/
          paths:
            - repo/deploy/ansible/inventory.txt
 
  configure-infrastructure:
    working_directory: ~/repo
    docker:
      - image: centos:centos8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yum install -y epel-release
            yum install -y tar gzip ansible
      # Reuse the workspace from the build job
      - attach_workspace:
          name: Attach Workspace
          at: ~/
      - add_ssh_keys:
          name: Add ssh keys with fingerprint
          fingerprints:
            - "e8:92:03:fd:e6:2d:df:65:71:97:7b:5e:fc:ac:25:91"
      - run:
          name: Configure server
          command: |
             cd ~/repo/deploy/ansible
             echo "$DOCKER_PASSWORD" > docker_password.txt
             ansible-playbook -i inventory.txt configure-server.yml
            # ansible-playbook --private-key secrets/udacity.pem -i deploy/ansible/inventory.txt deploy/ansible/configure-server.yml
               
workflows:
  default:
    jobs:
      - build-images
      - test-images:
          requires: [build-images]
          context: slack-secrets
      #- scan-images:
      #    requires: [build-images]
      - create-infrastructure:
          requires: [test-images]
          filters:
            branches:
              only: main
      - configure-infrastructure:
          requires: [create-infrastructure]

          