version: 2.1

jobs:
  build-images:
    #docker:
    #  - image: circleci/node:13.8.0    #circleci/python:3.6.7-stretch
    machine: true  #https://circleci.com/docs/2.0/building-docker-images/
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt update -y
            sudo apt install -y vim
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            sudo chmod +x /bin/hadolint
            #TODO - DOCKER CLI
      - run:
          name: Build Images
          command: |
            cd ~/repo
            docker build -f apache.Dockerfile --tag hello_app .
      - run:
          name: Lint Images
          command: |
            cd /home/circleci/repo
            hadolint apache.Dockerfile
      
      # build the application image
      - run: 
          name: Tag images
          command: |
            echo "$DOCKER_PASSWORD" > docker_password.txt
            cat docker_password.txt | docker login --username $DOCKER_ACCOUNT --password-stdin
            docker tag hello_app:latest $DOCKER_ACCOUNT/hello_app
      - run: 
          name: Push images
          command: |
            docker push cbath/hello_app
            
workflows:
  default:
    jobs:
      - build-images
      #- test-images:
      #    requires: [build-images]