---
- name: Log into Docker
  become: yes
  shell: |
    sudo echo "$DOCKER_PASSWORD" > /tmp/docker_password.txt
#sudo cat /tmp/docker_password.txt | docker login --username $DOCKER_ACCOUNT --password-stdin
#sudo docker login --username $DOCKER_ACCOUNT --password $DOCKER_PASSWORD

- name: Download Images
  become: yes
  shell: |
    sudo docker pull cbath/hello_app

- name: Deploy Pods
  become: yes
  shell: |
    sudo kubectl run hello-app --image=cbath/hello_app --port=80 --labels app=hello-app
#sudo docker container run -d -p 80:80 cbath/hello_app

- name: Update Port Listening for Cluster
  become: yes
  shell: |
    system sleep 120s
    echo $(sudo kubectl get pods)
    echo $(sudo kubectl get pods hello-app -o jsonpath='{.spec.containers[*].name}')