---
- name: Update Packages
  become: yes
  apt:
    update_cache: yes

- name: Upgrade Packages
  become: yes
  apt:
    upgrade: yes

- name: Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: Install Dependencies
  become: yes
  apt:
    name: ["curl","docker","docker.io"]
    state: latest
    update_cache: yes

# https://ubuntu.com/kubernetes/install
- name: Setup Kubernetes Node
  become: yes
  shell: |
    echo "Setting up Node"
#sudo docker container run -d -p 80:80 cbath/hello_app
#kubectl run $myapp --image=$imagename --port=80 --labels app=hello_app