---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm", "net-tools"]
    state: latest
    update_cache: yes

# https://docs.ansible.com/ansible/2.4/copy_module.html
- name: Copy Docker Credentials
  copy:
    src: ~/project/secrets/docker_password.txt
    dest: ~/docker_password.txt
    mode: 0400

- name: Log into Docker
  shell: |
    cat docker_password.txt | docker login --username $DOCKER_ACCOUNT --password-stdin

- name: Log into Docker
  shell: |
    echo "well hello there" > /tmp/hello.txt
