Description: >
    Craig Bath / Udacity IAC Project

# Declarations
# !Sub - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html
# !Ref - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html

Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub Capstone-${ID}
      GroupDescription: Allow port 22 and port 8080
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: udacity 
      ImageId: ami-083654bd07b5da81d   # Ubuntu 20.4 LTS
      Tags:
        - Key: Name
          Value: !Sub capstone-backend-${ID}

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
Outputs:
  BackendEndpoint:
    Description: The Endpoint of the backend application
    Value: !Join [ "", [ 'http://',!GetAtt EC2Instance.PublicDnsName ] ]
    Export:
      Name: !Sub ${ID}-PublicDnsName
  BackendIP:
    Description: The public IP of the backend application
    Value: !GetAtt EC2Instance.PublicIp
    Export:
      Name: !Sub ${ID}-PublicIP